package org.nsu.fit.tests.api;

import java.util.List;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;

import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import org.nsu.fit.services.rest.RestClient;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.nsu.fit.services.rest.data.TopUpBalancePojo;
import org.nsu.fit.services.rest.data.TopUpBalanceResponse;

public class BalanceTest {

    private RestClient restClient;
    private AccountTokenPojo adminToken;
    private CustomerPojo customerPojo;
    private AccountTokenPojo customerToken;

    @BeforeClass
    private void setUp() {
        restClient = new RestClient();
        adminToken = restClient.authenticate("admin", "setup");
        customerPojo = restClient.createAutoGeneratedCustomer(adminToken);
        customerToken = restClient.authenticate(customerPojo.login, customerPojo.pass);
    }

    @Test(description = "Initial value of balance is null.")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Balance feature.")
    public void checkInitialBalance() {
        List<CustomerPojo> customers =
                restClient.getCustomerByLogin(customerPojo.login, adminToken);

        Assert.assertEquals(customers.get(0).balance, 0);
    }

    @Test(description = "Update balance.")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Balance feature.")
    public void topUpBalance() {
        int money = 10;
        TopUpBalancePojo topUpBalancePojo = new TopUpBalancePojo();
        topUpBalancePojo.customerId = customerPojo.id;
        topUpBalancePojo.money = money;
        TopUpBalanceResponse topUpBalanceResponse = restClient.toUpBalance(topUpBalancePojo, customerToken);
        List<CustomerPojo> customers = restClient.getCustomerByLogin(customerPojo.login, customerToken);
        Assert.assertEquals(customers.get(0).balance, money);
    }
}
