package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;

import org.nsu.fit.utils.TestUtils;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import org.nsu.fit.services.rest.RestClient;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.ContactPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;

public class MeTest {

    private RestClient restClient;
    private AccountTokenPojo adminToken;

    @BeforeClass
    private void setUp() {
        restClient = new RestClient();
        adminToken = restClient.authenticate("admin","setup");
    }

    @Test(description = "me admin test")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Me test.")
    public void  meAdmin() {
        ContactPojo contactPojo = restClient.me(adminToken);

        Assert.assertEquals(contactPojo.login,"admin");
    }

    @Test(description = "Me customer test.")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Me test.")
    public void customer() {
        CustomerPojo customer1 = restClient.createAutoGeneratedCustomer(adminToken);
        AccountTokenPojo customerToken = restClient.authenticate(customer1.login, customer1.pass);
        CustomerPojo customer2 = restClient.me(customerToken);
        Assert.assertTrue(TestUtils.isEqual(customer1,customer2));
    }

}
